// ports/mitosis/output/svelte/src/ThinkingOrb.svelte
<script context="module" lang="ts">
  export interface ThinkingOrbProps {
    state?: OrbState;
    size?: OrbSize;
    theme?: OrbTheme;
    speed?: number;
    paused?: boolean;
    ariaLabel?: string;
  }
</script>

<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  import {
    attachController,
    createOrbController,
    controllerProps,
    getController,
  } from "./orb-controller";
  import { LABELS, type OrbSize, type OrbState, type OrbTheme } from "./types";

  export let state: ThinkingOrbProps["state"] = undefined;
  export let size: ThinkingOrbProps["size"] = undefined;
  export let theme: ThinkingOrbProps["theme"] = undefined;
  export let speed: ThinkingOrbProps["speed"] = undefined;
  export let paused: ThinkingOrbProps["paused"] = undefined;
  export let ariaLabel: ThinkingOrbProps["ariaLabel"] = undefined;
  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }

  let canvas;

  onMount(() => {
    const el = canvas;
    if (!el) return;
    attachController(
      el,
      createOrbController(
        el,
        controllerProps({
          state: state,
          size: size,
          theme: theme,
          speed: speed,
          paused: paused,
        })
      )
    );
  });

  function onUpdateFn_0(..._args: any[]) {
    const el = canvas;
    const ctl = getController(el);
    if (ctl) {
      ctl.applyProps(
        controllerProps({
          state: state,
          size: size,
          theme: theme,
          speed: speed,
          paused: paused,
        })
      );
    }
  }

  $: onUpdateFn_0(...[state, size, theme, speed, paused]);

  onDestroy(() => {
    const el = canvas;
    const ctl = getController(el);
    if (ctl) ctl.dispose();
  });
</script>

<!-- svelte-ignore a11y_no_interactive_element_to_noninteractive_role -->
<canvas
  style={stringifyStyles({
    width: size ?? 64,
    height: size ?? 64,
    display: "block",
  })}
  role="img"
  bind:this={canvas}
  aria-label={ariaLabel || LABELS[state ?? "working"]}
></canvas>

// ports/mitosis/output/react/src/ThinkingOrb.tsx
"use client";
import * as React from "react";
import { useRef, useEffect } from "react";

export interface ThinkingOrbProps {
  state?: OrbState;
  size?: OrbSize;
  theme?: OrbTheme;
  speed?: number;
  paused?: boolean;
  ariaLabel?: string;
}

import {
  attachController,
  createOrbController,
  controllerProps,
  getController,
} from "./orb-controller";
import { LABELS, type OrbSize, type OrbState, type OrbTheme } from "./types";

function ThinkingOrb(props: ThinkingOrbProps) {
  const canvas = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    const el = canvas.current;
    if (!el) return;
    attachController(
      el,
      createOrbController(
        el,
        controllerProps({
          state: props.state,
          size: props.size,
          theme: props.theme,
          speed: props.speed,
          paused: props.paused,
        })
      )
    );
  }, []);
  useEffect(() => {
    const el = canvas.current;
    const ctl = getController(el);
    if (ctl) {
      ctl.applyProps(
        controllerProps({
          state: props.state,
          size: props.size,
          theme: props.theme,
          speed: props.speed,
          paused: props.paused,
        })
      );
    }
  }, [props.state, props.size, props.theme, props.speed, props.paused]);
  useEffect(() => {
    return () => {
      const el = canvas.current;
      const ctl = getController(el);
      if (ctl) ctl.dispose();
    };
  }, []);

  return (
    <canvas
      role="img"
      ref={canvas}
      aria-label={props.ariaLabel || LABELS[props.state ?? "working"]}
      style={{
        width: props.size ?? 64,
        height: props.size ?? 64,
        display: "block",
      }}
    />
  );
}

export default ThinkingOrb;
